version: '3'

services:
  woot2rss:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/woot.db
      - LOG_FILE=/app/logs/woot2rss.log
    volumes:
      - woot-data:/app/data
      - woot-logs:/app/logs
    restart: unless-stopped

volumes:
  woot-data:
    driver: local
  woot-logs:
    driver: local